/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelly;
/**
 *home screen
 * @author kelly
 */
import java.awt.*;
import java.sql.*;
import java.util.logging.*;
/**
 *home screen
 * @author kelly
 */

public class HomeGUI extends javax.swing.JFrame
{

    /**
     * Creates new form HomeGUI
     */
    private DB db = new DB();
    private static User user;
    private javax.swing.JCheckBox[] cbArr = new javax.swing.JCheckBox[2000];
    private IngredientsArr ingrsArr;
    private int a = 0;

    public HomeGUI(User u)
    {
        initComponents();
        user = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlBackG = new javax.swing.JPanel();
        cmbMealPicker = new javax.swing.JComboBox<>();
        sclIngrs = new javax.swing.JScrollPane();
        pnlIngrs = new javax.swing.JPanel();
        sclRecip = new javax.swing.JScrollPane();
        pnlRecip = new javax.swing.JPanel();
        btnHelp = new javax.swing.JButton();
        btnSelectFridge = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        btnVeiwSummary = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home ");
        setMinimumSize(new java.awt.Dimension(517, 500));
        setResizable(false);

        pnlBackG.setBackground(new java.awt.Color(204, 255, 255));

        cmbMealPicker.setBackground(new java.awt.Color(102, 255, 255));
        cmbMealPicker.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbMealPicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All meal types", "Dinner", "Breakfast", "Lunch", "Desert" }));

        sclIngrs.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclIngrs.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        sclIngrs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        pnlIngrs.setBackground(new java.awt.Color(255, 255, 0));
        pnlIngrs.setMaximumSize(new java.awt.Dimension(228, 2147483647));
        pnlIngrs.setMinimumSize(new java.awt.Dimension(228, 400));
        pnlIngrs.setPreferredSize(new java.awt.Dimension(228, 400));
        pnlIngrs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sclIngrs.setViewportView(pnlIngrs);

        sclRecip.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclRecip.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlRecip.setBackground(new java.awt.Color(255, 0, 51));
        pnlRecip.setForeground(new java.awt.Color(255, 255, 255));
        pnlRecip.setMinimumSize(new java.awt.Dimension(300, 400));
        pnlRecip.setPreferredSize(new java.awt.Dimension(300, 400));
        pnlRecip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sclRecip.setViewportView(pnlRecip);

        btnHelp.setBackground(new java.awt.Color(102, 255, 255));
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHelpActionPerformed(evt);
            }
        });

        btnSelectFridge.setBackground(new java.awt.Color(102, 255, 255));
        btnSelectFridge.setText("Select Fridge");
        btnSelectFridge.setEnabled(false);
        btnSelectFridge.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSelectFridgeActionPerformed(evt);
            }
        });

        btnSort.setBackground(new java.awt.Color(102, 255, 255));
        btnSort.setText("Sort");
        btnSort.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSort.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSortActionPerformed(evt);
            }
        });

        btnInventory.setBackground(new java.awt.Color(102, 255, 255));
        btnInventory.setText("Inventory Manager");
        btnInventory.setToolTipText("click this to open the inventory manager");
        btnInventory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnInventoryActionPerformed(evt);
            }
        });

        btnContinue.setBackground(new java.awt.Color(102, 255, 255));
        btnContinue.setText("Contiue");
        btnContinue.setEnabled(false);
        btnContinue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinue.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnContinueActionPerformed(evt);
            }
        });

        btnVeiwSummary.setBackground(new java.awt.Color(102, 255, 255));
        btnVeiwSummary.setText("Veiw Summary");
        btnVeiwSummary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeiwSummary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVeiwSummaryActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Kelly's Recipes");
        lblTitle.setMaximumSize(new java.awt.Dimension(200, 29));
        lblTitle.setMinimumSize(new java.awt.Dimension(200, 29));
        lblTitle.setName(""); // NOI18N

        javax.swing.GroupLayout pnlBackGLayout = new javax.swing.GroupLayout(pnlBackG);
        pnlBackG.setLayout(pnlBackGLayout);
        pnlBackGLayout.setHorizontalGroup(
            pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackGLayout.createSequentialGroup()
                        .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sclIngrs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cmbMealPicker, 0, 160, Short.MAX_VALUE))
                        .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackGLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(sclRecip, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackGLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHelp))))
                    .addGroup(pnlBackGLayout.createSequentialGroup()
                        .addComponent(btnSelectFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackGLayout.createSequentialGroup()
                                .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlBackGLayout.createSequentialGroup()
                                .addComponent(btnVeiwSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBackGLayout.setVerticalGroup(
            pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackGLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMealPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sclRecip, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(sclIngrs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectFridge)
                    .addComponent(btnSort))
                .addGap(18, 18, 18)
                .addComponent(btnContinue)
                .addGap(18, 18, 18)
                .addGroup(pnlBackGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVeiwSummary)
                    .addComponent(btnInventory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(533, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVeiwSummaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVeiwSummaryActionPerformed
    {//GEN-HEADEREND:event_btnVeiwSummaryActionPerformed
        new CookingSummaryGUI(user).setVisible(true);
    }//GEN-LAST:event_btnVeiwSummaryActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSortActionPerformed
    {//GEN-HEADEREND:event_btnSortActionPerformed
        pnlIngrs.repaint();
        pnlIngrs.removeAll();
        pnlRecip.removeAll();
        pnlRecip.repaint();

        ingrsArr = new IngredientsArr(cmbMealPicker.getSelectedItem().toString());

        Ingredients[] ingrs;
        ingrs = ingrsArr.getIngArr();
        while (a < ingrsArr.getSize())
        {
            String d = ingrs[a].getIngName();
            cbArr[a] = new javax.swing.JCheckBox(d);
            pnlIngrs.add(cbArr[a], new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25 * (a), 200, 20));
            cbArr[a].setVisible(true);
            a++;
        }

        btnContinue.setEnabled(true);
        btnSelectFridge.setEnabled(true);
        pnlIngrs.updateUI();
    }//GEN-LAST:event_btnSortActionPerformed


    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinueActionPerformed
    {//GEN-HEADEREND:event_btnContinueActionPerformed
        pnlRecip.repaint();
        pnlIngrs.repaint();

        Ingredients[] ingr = ingrsArr.getIngArr();
        Ingredients[] ingr2 = new Ingredients[ingrsArr.getSize()];
        int b = 0, c = 0;

        for (int i = 0; i < a; i++)
        {
            if (cbArr[b].isSelected() == true)
            {
                ingr2[c] = ingr[b];
                b++;
                c++;
            } else
            {
                b++;
            }
        }
        IngredientsArr ingrsArr2 = new IngredientsArr(ingr2, c);
        RecipeArr resArr = new RecipeArr(ingrsArr2, c, cmbMealPicker.getSelectedItem().toString());
        Recipe[] resp = resArr.getResArr();
        javax.swing.JButton[] btnArr = new javax.swing.JButton[2000];
        int a = 0;
        while (a < resArr.getSize())
        {
            String d = resp[a].getResName();
            btnArr[a] = new javax.swing.JButton(d);
            pnlRecip.add(btnArr[a], new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35 * (a), 160, 30));
            btnArr[a].setVisible(true);
            btnArr[a].setBackground(Color.yellow);

            btnArr[a].addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    try
                    {
                        ResultSet rs = db.query("SELECT id FROM tblrecipies WHERE recipe LIKE '" + evt.getActionCommand() + "'");
                        rs.next();
                        int id = rs.getInt("id");
                        Recipe rec = new Recipe(evt.getActionCommand(), id);
                        new BookGUI(user, rec).setVisible(true);
                    } catch (SQLException ex)
                    {
                        Logger.getLogger(HomeGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            a++;
        }
        pnlIngrs.removeAll();
        btnSelectFridge.setEnabled(false);
        pnlIngrs.repaint();
        pnlRecip.updateUI();
    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHelpActionPerformed
    {//GEN-HEADEREND:event_btnHelpActionPerformed
        new HelpGUI().setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnSelectFridgeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSelectFridgeActionPerformed
    {//GEN-HEADEREND:event_btnSelectFridgeActionPerformed
        try
        {
            ResultSet rs = db.query("SELECT poolID FROM tblusers WHERE userName LIKE '" + user.getUserName() + "'");
            rs.next();
            String pool = rs.getString("poolID");
            InventoryArr invent = new InventoryArr(pool);
            Inventory[] inArr = invent.getInvenArr();
            int b = 0;
            while (cbArr[b].isVisible() == true)
            {
                for (int i = 0; i < invent.getSize(); i++)
                {
                    if (cbArr[b].getText().equalsIgnoreCase(inArr[i].getIngname()))
                    {
                        cbArr[b].setSelected(true);
                    }
                }
                b++;
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(HomeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectFridgeActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInventoryActionPerformed
    {//GEN-HEADEREND:event_btnInventoryActionPerformed
        new InventoryGUI(user).setVisible(true);
    }//GEN-LAST:event_btnInventoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new HomeGUI(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnContinue;
    javax.swing.JButton btnHelp;
    javax.swing.JButton btnInventory;
    javax.swing.JButton btnSelectFridge;
    javax.swing.JButton btnSort;
    javax.swing.JButton btnVeiwSummary;
    javax.swing.JComboBox<String> cmbMealPicker;
    javax.swing.JLabel lblTitle;
    javax.swing.JPanel pnlBackG;
    javax.swing.JPanel pnlIngrs;
    javax.swing.JPanel pnlRecip;
    javax.swing.JScrollPane sclIngrs;
    javax.swing.JScrollPane sclRecip;
    // End of variables declaration//GEN-END:variables
}
