/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelly;
/**
 *sign up screen
 * @author kelly
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *sign up screen
 * @author kelly
 */
public class SignUpGUI extends javax.swing.JFrame
{

    /**
     * Creates new form SignUpGUI
     */
    private DB db = new DB();
    private String user = "", pass = "";

    public SignUpGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txfUserName = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        pwfPass = new javax.swing.JPasswordField();
        lblConfPass = new javax.swing.JLabel();
        pwfConfPass = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        cmbInventoryPicker = new javax.swing.JComboBox<>();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome To Kelly's Recipes");

        lblUserName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUserName.setText("User Name");

        lblPass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPass.setText("Password");
        lblPass.setToolTipText("");

        lblConfPass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblConfPass.setText("Confirm Password");
        lblConfPass.setToolTipText("");

        btnLogIn.setBackground(new java.awt.Color(102, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLogInActionPerformed(evt);
            }
        });

        cmbInventoryPicker.setBackground(new java.awt.Color(102, 255, 255));

        lblInfo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInfo.setText(" ");
        lblInfo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUserName)
                        .addGap(60, 60, 60)
                        .addComponent(txfUserName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbInventoryPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass)
                            .addComponent(lblConfPass))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwfConfPass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pwfPass)))
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(pwfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwfConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfPass))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogIn)
                    .addComponent(cmbInventoryPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(365, 256));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLogInActionPerformed
    {//GEN-HEADEREND:event_btnLogInActionPerformed
        try
        {
            ResultSet rs = db.query("SELECT * FROM tblusers");
            user = txfUserName.getText();
            boolean userExist = false;

            while (rs.next() && userExist == false)
            {
                if (user.equals(rs.getString("userName")))
                {
                    userExist = true;
                }
            }

            if (userExist == false)
            {
                pass = pwfPass.getText();
                String conf = pwfConfPass.getText();
                if (conf.equals(pass))
                {
                    boolean poolExtant;
                    String newPool = "";

                    do
                    {
                        poolExtant = false;
                        newPool = JOptionPane.showInputDialog("enter a name for your new inventory pool. It must be unique");
                        rs = db.query("SELECT poolName FROM tblpools");
                        while (rs.next() && poolExtant == false)
                        {
                            if (newPool.equals(rs.getString("poolName")))
                            {
                                poolExtant = true;
                            }
                        }
                    } while (poolExtant == true);

                    int poolID;
                    if (cmbInventoryPicker.getSelectedItem().equals("create new"))
                    {
                        db.update("INSERT INTO kellygr11pat.tblpools (`poolName`) VALUES ('" + newPool + "')");
                        rs = db.query("SELECT MAX(poolID) AS pool FROM tblpools");
                        rs.next();
                        poolID = rs.getInt("pool");
                    } else
                    {
                        rs = db.query("SELECT poolID FROM tblpools WHERE poolName LIKE '" + cmbInventoryPicker.getSelectedItem() + "'");
                        rs.next();
                        poolID = rs.getInt("poolID");
                    }

                    db.update("INSERT INTO tblusers VALUES ('" + user + "','" + pass + "', " + poolID + ")");
                    lblInfo.setText("User added");
                    User newUser = new User(user, pass);
                    new HomeGUI(newUser).setVisible(true);
                    this.dispose();
                } else
                {
                    lblInfo.setText("Passwords don't match");
                }
            } else
            {
                lblInfo.setText("User exists: use a different user name");
            }
        } catch (SQLException s)
        {
            Logger.getLogger(LogInGUI.class.getName()).log(Level.SEVERE, null, s);
            lblInfo.setText("Cannot load user");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try
        {
            ResultSet rs = db.query("SELECT * FROM tblpools");
            while (rs.next())
            {
                cmbInventoryPicker.addItem(rs.getString("poolName"));
            }
            cmbInventoryPicker.addItem("create new");
        } catch (SQLException ex)
        {
            Logger.getLogger(SignUpGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SignUpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnLogIn;
    javax.swing.JComboBox<String> cmbInventoryPicker;
    javax.swing.JPanel jPanel1;
    javax.swing.JLabel lblConfPass;
    javax.swing.JLabel lblInfo;
    javax.swing.JLabel lblPass;
    javax.swing.JLabel lblTitle;
    javax.swing.JLabel lblUserName;
    javax.swing.JPasswordField pwfConfPass;
    javax.swing.JPasswordField pwfPass;
    javax.swing.JTextField txfUserName;
    // End of variables declaration//GEN-END:variables
}
